[main]
font=JetBrains Mono:size=10

[security]
osc52=enabled

[mouse]
hide-when-typing=true

[key-bindings]
search-start=Control+f
fullscreen=Control+Shift+f

[search-bindings]
find-prev=Control+Shift+f
find-next=Control+f
cursor-left=Control+h
cursor-left-word=Control+Shift+h Control+Left
cursor-right=Control+l
cursor-right-word=Control+Shift+l Control+Right

[colors-dark]
alpha=1
background=0f0f0f
foreground=ebe0e0

# black
regular0=141414
bright0=272a28

# red
regular1=f16e65
bright1=f2aba6

# green
regular2=7ec97e
bright2=b7e1b7

# yellow
regular3=e8a069
bright3=f6eba2

# blue
regular4=6199d1
bright4=94b3d1

# magenta
regular5=e59acc
bright5=ecb6da

# cyan
regular6=6fc3b5
bright6=a5d9d1

# white
regular7=ebe0e0
bright7=ebe0e0
